use interpolating quotes only when intentionally interpolating

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -10,20 +10,20 @@
 # - starts the test suite witin a VM
 # - stops the VM after the test suite is done
 
-export BOXES=""
-export FILES=""
-export KEEP_RUNNING=""
+export BOXES=''
+export FILES=''
+export KEEP_RUNNING=''
 
 # global variable for script exit value
 export EXIT_VALUE=0
 
 display_help() {
-	echo "Usage:"
-	echo "  ./run_tests                      # runs tests on default VM ubuntu"
-	echo "  ./run_tests -m ubuntu            # runs tests on ubuntu VM"
-	echo "  ./run_tests -m ubuntu -m centos  # runs tests on ubuntu and cents VMs"
-	echo "  ./run_tests tests/some_test      # run a single test file"
-	echo "  ./run_tests --keep-running       # don't stop vagrant after the tests are done"
+	echo 'Usage:'
+	echo '  ./run_tests                      # runs tests on default VM ubuntu'
+	echo '  ./run_tests -m ubuntu            # runs tests on ubuntu VM'
+	echo '  ./run_tests -m ubuntu -m centos  # runs tests on ubuntu and cents VMs'
+	echo '  ./run_tests tests/some_test      # run a single test file'
+	echo '  ./run_tests --keep-running       # don'\''t stop vagrant after the tests are done'
 }
 
 parse_arguments() {
@@ -32,11 +32,11 @@ parse_arguments() {
 		case "$1" in
 		-m | --machine)
 			local machine="$2"
-			if [[ "$machine" == "ubuntu" || "$machine" == "centos" ]]; then
+			if [[ "$machine" == 'ubuntu' || "$machine" == 'centos' ]]; then
 				BOXES="$BOXES $machine"
 			else
 				echo "Unknown machine '$machine'"
-				echo ""
+				echo
 				display_help
 				exit 1
 			fi
@@ -44,7 +44,7 @@ parse_arguments() {
 			;;
 
 		-k | --keep-running)
-			KEEP_RUNNING="true"
+			KEEP_RUNNING='true'
 			shift
 			;;
 
@@ -61,7 +61,7 @@ parse_arguments() {
 
 		-* )
 			echo "Error: Unknown option: $1" >&2
-			echo ""
+			echo
 			display_help
 			exit 1
 			;;
@@ -75,7 +75,7 @@ parse_arguments() {
 
 	# default options
 	if [[ -z "$BOXES" ]]; then
-		BOXES="ubuntu"
+		BOXES='ubuntu'
 	fi
 }
 
@@ -96,13 +96,13 @@ stop_vagrant() {
 		VAGRANT_CWD=lib/tmux-test/ vagrant halt "$box"
 	else
 		echo
-		echo "--keep-running option set, Vagrant not halted"
+		echo '--keep-running option set, Vagrant not halted'
 	fi
 }
 
 run_tests() {
 	local box="$1"
-	local test_file="/vagrant/tests/run_tests_in_isolation"
+	local test_file='/vagrant/tests/run_tests_in_isolation'
 	echo "Running test suite on $box from: $test_file"
 	echo
 	VAGRANT_CWD=lib/tmux-test/ vagrant ssh "$box" -c "cd /vagrant; $test_file $FILES"
@@ -112,9 +112,9 @@ exit_message() {
 	local exit_val="$1"
 	echo
 	if [[ "$exit_val" -eq 0 ]]; then
-		echo "Success, tests pass!"
+		echo 'Success, tests pass!'
 	else
-		echo "Tests failed!" 1>&2
+		echo 'Tests failed!' 1>&2
 	fi
 }
 
